[Proxies]
# Proxies for required interfaces
CameraRGBDSimple = "camerargbdsimple:tcp -h localhost -p 12001"
Lidar3D = "lidar3d:tcp -h localhost -p 11995"  # Filter

# --- Common Agent Data ---
[Agent]
id = 6 # Change id
name = "robot_concept"

# --- Single Instance Configuration ---
# Use this if you only have one graph.
configFile = "room.json"
domain = 0
tree = true
graph = true
2d = true
3d = false

# --- Multiple Instance Template ---
# If you define multiple instances, the single instance config above will be ignored.
# [Agent.instance_name]
# configFile = ""
# domain = 1
# tree = true
# graph = true
# 2d = true
# 3d = true

[Period]
Compute = 100
Emergency = 500

[Yolo]
model_path  = "yolo26l-seg.onnx"
conf_thresh = 0.25
iou_thresh  = 0.45
use_gpu     = true
use_trt     = false

[Component.Debug]
Verbose = false

[Ice]
Warn.Connections = "0"
Trace.Network = "0"
Trace.Protocol = "0"
MessageSizeMax = "20004800"
