#!/usr/bin/env python3
"""Fit one capsule (axis, center, half-length, radius) to each Kinova arm link STL.

The self-projection viewer / calibration residual needs a faithful-but-analytic
geometric model of the arm. The URDF collision geometry is raw STL meshes (no
primitives), so we fit a capsule per link here, ONCE, and emit a C++ header.

AXIS = the KINEMATIC CHAIN DIRECTION (the offset to the next joint, read from the
URDF as that joint's <origin xyz>, which is already expressed in this link's frame).
We do NOT use the mesh's PCA principal axis: it is reliable only for the elongated
links and DEGENERATE for the squat wrist links (λ1≈λ2), where a small asymmetry —
e.g. the ZED camera housing on the bracelet — tilts it arbitrarily. The chain
direction is well-defined for every link and matches PCA where PCA was good, so it
fixes the wrist/bracelet tilt without disturbing the long links.

Per mesh (vertices are in the link frame — every arm-link collision <origin> is
identity), given the chain axis:
  center      = midpoint of the vertex projection onto the axis (through the centroid)
  half_length = half the axial extent (robust 1/99 percentile)
  radius      = robust (95th pct) perpendicular distance to the axis

Usage:
  python3 fit_link_capsules.py            # prints + writes the header (run from common/kinematics/)
"""
import sys
import xml.etree.ElementTree as ET

import numpy as np
import trimesh

MESH_DIR = "/home/pbustos/robocomp/components/webots-kinova/protos/kinova_arm_meshes"
URDF     = "gen3_robotiq_2f_85-mod.urdf"
OUT_HEADER = "self_projection_capsules.h"   # written next to this script (common/kinematics/)

# Radius = this percentile of the vertices' perpendicular distance to the axis.
# The cylindrical SURFACE piles up at the core radius; a low percentile (~50, median)
# tracks that core, a high one (95) gets pulled out by flanges/bumps (e.g. the bracelet
# camera housing) and over-states the radius — which biases the predicted surface too
# close (a negative depth residual). 50 = core radius.
RADIUS_PCT = 50

# Mesh filenames (order arm_mesh_link_poses() emits) -> their URDF link name.
MESH2LINK = [
    ("base_link.STL",                  "base_link"),
    ("shoulder_link.STL",              "shoulder_link"),
    ("half_arm_1_link.STL",            "half_arm_1_link"),
    ("half_arm_2_link.STL",            "half_arm_2_link"),
    ("forearm_link.STL",               "forearm_link"),
    ("spherical_wrist_1_link.STL",     "spherical_wrist_1_link"),
    ("spherical_wrist_2_link.STL",     "spherical_wrist_2_link"),
    ("bracelet_with_vision_link.STL",  "bracelet_link"),
]


def chain_directions():
    """link name -> unit vector toward its child joint (in the link frame)."""
    root = ET.parse(URDF).getroot()
    out = {}
    for j in root.findall("joint"):
        parent = j.find("parent").get("link")
        o = j.find("origin")
        xyz = np.array([float(x) for x in o.get("xyz", "0 0 0").split()]) if o is not None else np.zeros(3)
        n = np.linalg.norm(xyz)
        if parent not in out and n > 1e-6:
            out[parent] = xyz / n
    return out


def pca_axis(Q):
    w, U = np.linalg.eigh(Q.T @ Q / len(Q))
    order = np.argsort(w)[::-1]
    return U[:, order[0]], (np.sqrt(w[order[0]] / w[order[1]]) if w[order[1]] > 0 else np.inf)


def fit_capsule(V, axis):
    c0 = V.mean(axis=0)
    Q = V - c0
    t = Q @ axis
    tlo, thi = np.percentile(t, 1), np.percentile(t, 99)
    half_length = 0.5 * (thi - tlo)
    center = c0 + axis * (0.5 * (thi + tlo))
    perp = Q - np.outer(t, axis)
    radius = float(np.percentile(np.linalg.norm(perp, axis=1), RADIUS_PCT))
    return center, half_length, radius


def main():
    chain = chain_directions()
    rows = []
    for name, link in MESH2LINK:
        V = np.asarray(trimesh.load(f"{MESH_DIR}/{name}", force="mesh").vertices)
        _, ratio = pca_axis(V - V.mean(axis=0))
        # Chain (kinematic) axis is the model; PCA only as a last-resort fallback.
        axis = chain.get(link)
        src = "chain"
        if axis is None:
            axis, _ = pca_axis(V - V.mean(axis=0)); src = "pca"
        center, hl, radius = fit_capsule(V, axis)
        rows.append((name, axis, center, hl, radius))
        print(f"{name:30s} [{src}] axis=({axis[0]:+.3f},{axis[1]:+.3f},{axis[2]:+.3f}) "
              f"center=({center[0]:+.3f},{center[1]:+.3f},{center[2]:+.3f}) "
              f"L/2={hl:.3f} r={radius:.3f}  (pca λ1/λ2={ratio:.2f})")

    lines = [
        "#pragma once",
        "",
        "// AUTO-GENERATED by common/kinematics/fit_link_capsules.py — do not edit by hand.",
        "// One capsule fitted to each arm-link STL, in the link (joint) frame. The axis is the",
        "// KINEMATIC chain direction (offset to the next joint), NOT the mesh PCA axis, which is",
        "// degenerate for the squat wrist links. Consumed by the self_calibration aura + residual.",
        "",
        "#include <array>",
        "#include <string_view>",
        "",
        "struct LinkCapsule",
        "{",
        "    std::string_view mesh;   // STL filename (matches Kinematics::arm_mesh_link_poses)",
        "    double ax, ay, az;       // unit axis, link frame",
        "    double cx, cy, cz;       // capsule axis center, link frame (m)",
        "    double half_length;      // m",
        "    double radius;           // m",
        "};",
        "",
        f"inline constexpr std::array<LinkCapsule, {len(rows)}> LINK_CAPSULES = {{{{",
    ]
    for name, axis, c, hl, r in rows:
        lines.append(
            f'    {{"{name}", {axis[0]:+.6f}, {axis[1]:+.6f}, {axis[2]:+.6f}, '
            f'{c[0]:+.6f}, {c[1]:+.6f}, {c[2]:+.6f}, {hl:.6f}, {r:.6f}}},'
        )
    lines.append("}};")
    lines.append("")
    with open(OUT_HEADER, "w") as f:
        f.write("\n".join(lines))
    print(f"\nwrote {OUT_HEADER}")


if __name__ == "__main__":
    sys.exit(main())
