#pragma once

// AUTO-GENERATED by common/kinematics/fit_link_capsules.py — do not edit by hand.
// One capsule fitted to each arm-link STL, in the link (joint) frame. The axis is the
// KINEMATIC chain direction (offset to the next joint), NOT the mesh PCA axis, which is
// degenerate for the squat wrist links. Consumed by the self_calibration aura + residual.

#include <array>
#include <string_view>

struct LinkCapsule
{
    std::string_view mesh;   // STL filename (matches Kinematics::arm_mesh_link_poses)
    double ax, ay, az;       // unit axis, link frame
    double cx, cy, cz;       // capsule axis center, link frame (m)
    double half_length;      // m
    double radius;           // m
};

inline constexpr std::array<LinkCapsule, 8> LINK_CAPSULES = {{
    {"base_link.STL", +0.000000, +0.000000, +1.000000, -0.002543, -0.000727, +0.085425, 0.085425, 0.045513},
    {"shoulder_link.STL", +0.000000, +0.041831, -0.999125, -0.000018, -0.011801, -0.087677, 0.085044, 0.038042},
    {"half_arm_1_link.STL", +0.000000, -0.999541, -0.030288, +0.000024, -0.090232, -0.017326, 0.134174, 0.039315},
    {"half_arm_2_link.STL", +0.000000, +0.030288, -0.999541, +0.000119, -0.012456, -0.128708, 0.125993, 0.037715},
    {"forearm_link.STL", +0.000000, -0.999533, -0.030572, -0.000112, -0.088236, -0.020186, 0.132277, 0.034448},
    {"spherical_wrist_1_link.STL", +0.000000, +0.001653, -0.999999, -0.000061, -0.014935, -0.071229, 0.068692, 0.031200},
    {"spherical_wrist_2_link.STL", +0.000000, -0.999999, -0.001653, -0.000150, -0.042471, -0.014462, 0.075850, 0.031876},
    {"bracelet_with_vision_link.STL", +0.000000, +0.000000, -1.000000, +0.000700, -0.044211, -0.033462, 0.030963, 0.033279},
}};
