#!/usr/bin/env python3
"""
make_table_obj.py — generate meshes/table.obj: a plain rectangular four-legged table.

WHY THIS EXISTS RATHER THAN A DOWNLOADED MODEL. The mesh this replaced was an
office/trestle desk (two panel end-supports and a modesty panel, no legs) carrying no
provenance beyond a "# https://github.com/mikedh/trimesh" line, and the display mesh has
to satisfy a contract no stock model happens to meet:

  THE mesh_path CONTRACT (viewer3d/src/voxel_opengl_viewer.cpp, append_scaled_mesh):
  the OBJ is a UNIT template in the ROOM frame, Z up — footprint x, y in [-0.5, 0.5] and
  height z in [0, 1]. The viewer scales it by the fitted box (w, d, h), yaws it and anchors
  it to the floor. A model off the shelf has to be re-centred, re-axed and re-normalised
  before it can be used at all, at which point its geometry is the only thing you kept.

  ALSO: the FILENAME IS A SIGNAL. table_concept publishes round_table.obj vs table.obj to
  say which shape its free-energy model evidence preferred, and the controller and both
  viewers read that name (table_scene_graph.cpp:156). This file must stay `table.obj`.

Everything below is a fraction of the fitted box, so the proportions hold at any table
size. At a typical 1.2 x 0.8 x 0.75 m table they come out as: 4.1 cm top, 6.6 x 4.4 cm
legs inset 3.6 cm from the edge, and a 7.5 cm apron — ordinary dining-table numbers.

Run from the component root:   python3 scripts/make_table_obj.py
"""

from pathlib import Path

# ── Proportions (fractions of the fitted box; footprint is 1.0 x 1.0, height 1.0) ────────
TOP_T = 0.055   # tabletop thickness
LEG_S = 0.055   # leg cross-section (square in template units)
LEG_IN = 0.030  # inset of the leg's OUTER face from the table edge — the overhang
APRON_H = 0.100  # apron/skirt depth below the top
APRON_T = 0.030  # apron rail thickness
APRON_IN = 0.055  # inset of the apron's OUTER face from the table edge

HALF = 0.5


def box(o, x0, x1, y0, y1, z0, z1):
    """Append one axis-aligned box as 6 quads. Winding is CCW seen from OUTSIDE, so the
    viewer's per-triangle QVector3D::normal() points out of the solid and its shading
    reads as a lit surface rather than an inside-out one."""
    faces = [
        # (corners in CCW order from outside, uv axes)
        ([(x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1)], "yz"),   # +X
        ([(x0, y1, z0), (x0, y0, z0), (x0, y0, z1), (x0, y1, z1)], "yz"),   # -X
        ([(x1, y1, z0), (x0, y1, z0), (x0, y1, z1), (x1, y1, z1)], "xz"),   # +Y
        ([(x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1)], "xz"),   # -Y
        ([(x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)], "xy"),   # +Z
        ([(x0, y1, z0), (x1, y1, z0), (x1, y0, z0), (x0, y0, z0)], "xy"),   # -Z
    ]
    for corners, axes in faces:
        idx = []
        for (x, y, z) in corners:
            # Planar UVs over the face's own extent. The shipped basecolour is a flat
            # swatch, so this only has to be sane, not grain-aligned.
            u, v = {"yz": (y, z), "xz": (x, z), "xy": (x, y)}[axes]
            o["v"].append((x, y, z))
            o["vt"].append((u + HALF, v))
            idx.append(len(o["v"]))
        a, b, c, d = idx
        o["f"].append((a, b, c))
        o["f"].append((a, c, d))


def build():
    o = {"v": [], "vt": [], "f": []}

    top_z0 = 1.0 - TOP_T
    box(o, -HALF, HALF, -HALF, HALF, top_z0, 1.0)                    # tabletop

    # Apron: four rails just under the top, spanning between the legs. This is what makes a
    # table read as a table instead of a slab on four sticks, and it is also the surface an
    # under-table residual sees, so it is worth having in the display model.
    ap_o = HALF - APRON_IN              # apron outer face
    ap_i = ap_o - APRON_T               # apron inner face
    ap_z0, ap_z1 = top_z0 - APRON_H, top_z0
    box(o, -ap_o, ap_o, ap_i, ap_o, ap_z0, ap_z1)                    # +Y rail
    box(o, -ap_o, ap_o, -ap_o, -ap_i, ap_z0, ap_z1)                  # -Y rail
    box(o, ap_i, ap_o, -ap_i, ap_i, ap_z0, ap_z1)                    # +X rail (between them)
    box(o, -ap_o, -ap_i, -ap_i, ap_i, ap_z0, ap_z1)                  # -X rail

    # Four legs, floor to the underside of the top.
    lg_o = HALF - LEG_IN                # leg outer face
    lg_i = lg_o - LEG_S                 # leg inner face
    for sx in (+1, -1):
        for sy in (+1, -1):
            x0, x1 = sorted((sx * lg_o, sx * lg_i))
            y0, y1 = sorted((sy * lg_o, sy * lg_i))
            box(o, x0, x1, y0, y1, 0.0, top_z0)

    return o


def write(o, path):
    with open(path, "w") as f:
        f.write("# Rectangular four-legged table, generated by scripts/make_table_obj.py\n")
        f.write("# UNIT TEMPLATE, room frame Z up: x,y in [-0.5,0.5], z in [0,1]. Do not\n")
        f.write("# re-scale or re-centre — viewer3d scales this by the fitted (w,d,h).\n")
        f.write("mtllib material.mtl\n\no table\nusemtl Mesa1\n")
        for x, y, z in o["v"]:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for u, v in o["vt"]:
            f.write(f"vt {u:.6f} {v:.6f}\n")
        for a, b, c in o["f"]:
            f.write(f"f {a}/{a} {b}/{b} {c}/{c}\n")


if __name__ == "__main__":
    mesh = build()
    out = Path(__file__).resolve().parent.parent / "meshes" / "table.obj"
    write(mesh, out)
    xs = [v[0] for v in mesh["v"]]
    ys = [v[1] for v in mesh["v"]]
    zs = [v[2] for v in mesh["v"]]
    print(f"{out}: {len(mesh['v'])} verts, {len(mesh['f'])} tris")
    print(f"  bbox x[{min(xs):+.3f},{max(xs):+.3f}] "
          f"y[{min(ys):+.3f},{max(ys):+.3f}] z[{min(zs):+.3f},{max(zs):+.3f}]")
